ARG NODE_VER="8.9.4"

FROM node:${NODE_VER}-alpine as RELEASE

ENV HOME_DIR "opt/auth-service"

RUN mkdir -p $HOME_DIR
WORKDIR $HOME_DIR

COPY package.json ./

RUN npm config set loglevel warn
RUN npm install --only=production --no-package-lock

COPY /src ./src/

ARG PORT=3001
ENV PORT=${PORT}
EXPOSE $PORT
