ARG NODE_VER="14.3.0"
ARG PORT=3010

FROM node:${NODE_VER}-alpine as RELEASE

ENV HOME_DIR "opt/auth-service"

RUN mkdir -p $HOME_DIR
WORKDIR $HOME_DIR

COPY package.json ./

RUN npm config set loglevel warn
RUN npm install --quiet --only=production --no-package-lock

COPY /src ./src/

ENV PORT=${PORT}
EXPOSE $PORT

CMD ["npm", "run", "start"]
