name: Ensure GitHub Labels

on: push

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v4.0.0
        with:
          yaml_file: .github/labels.yaml
          skip_delete: false
          dry_run: false
          exclude: |
            help*
            *issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
